---
 - name: Compaile Required Softwares For Debian
   apt:
      name: "{{item}}"
      state: present
   with_items: 
      - build-essential
      - zlib1g-dev
      - libssl-dev
   when: ansible_os_family   
 - name: Compaile Required Softwares For RedHat
   yum:
       name: "{{item}}"
       state: present
   with_items:  
      - gcc
      - openssl-devel
      - zlib-devel
   when: ansible_os_family   
       

